### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by lahhn** [ravarage/ASSR-Anime-Sign-Song-Ripper-#1]
Installed v1.0.6 on a Win10 machine, but on launch the application closes immediately with the window appearing for less than a second. 
Tried Windows compatibility settings and administrator execution with no luck.
Installed v1.0.5 with the same results.

**Comment by ravarage** [comment]
thank you, it will be fixed in next version, I am out of town for few days hopefully it will be fixed before Sunday,I wasn't aware of it so thank you

Temporary solution 
open C:\Users\Your User\ASSR Setting\asscconfig.ini
and add this line and save it 
[ffprobe location]
dir = C:\Program Files\MKVToolNix

**Comment by ravarage** [comment]
I fix the issues and update is online 
https://github.com/ravarage/ASSR-Anime-Sign-Song-Ripper-/releases/tag/1.0.7
thank you for reporting the issue
